### ISSUE TITLE
RISECamp Tutorial Final Feedback and Todo

### ISSUE THREAD

**Issue by simon-mo** [ucbrise/clipper-tutorials#17]
# Tutorial Todos

## Due
- [ ] Draft by Friday so Dan can make some edits. 
- [ ] Test possible collision with Integration (Hari)

## Split into 3 notebooks (Simon)
- [x] TOC, Summary, Intro
	- [ ] Link to part1 and part2
- [x] Part 1
- [x] Part 2

## Poll (Simon)
- [x] waiting on Joey to edit the poll
- [x] Add it to the end of the tutorial (part 1, 2)

## Less reading (Simon)
- [x] Abstract paragraphs into optional paragraphs
	- [x] Each section should only have 2-4 sentences: here's what you are going to do and why are you going to do it.
	- [x] Other, hidden optional sub-section. Drop-down
- [ ] Add a new `util.py` file to make code shorter. 
- [x] Dockerfile: 
	- [x] Make detail description optional
	- [x] Add description as comments in actual docker file. 

## New small section (Rehan)
- [x] pytorch: add a cell after batching: "bring your url"
- [x] at the end, ask them to check grafana to see update

## Nit (Rehan)
- [x] Make sure the links open in new tabs, ex the Grafana link. change markdown links-> html links in `display(Markdown())`
- [x] Reset fixme
- [x] Reset collapse cell / or just use drop-down
- [x] Add stop_all in part 1 in the beginning
- [x] `make -j16` for Darknet
- [x] at the end, comment out stop_all
- [ ] Matplotlib will warning in plotting code for legend missing handles. We will fix it. 
- [x] Part 1 text: Change ‘word count model’ -> ‘flowercat model’
- [x] Replica image has 4 replicas although we are only doing 3 replicas
- [x] In the overview section, change part 1 to fix minor typos:
	Part 1 provides a detailed explanation of Clipper, its architecture, and the python API. It uses the deployment of a scikit-learn model that classifies flowers based on their Sepal Length and Sepal Width as example.

**Comment by simon-mo** [comment]
Simon
- [ ] Simon enable docker network in a fork using docker `campnet_clipper`
